# Face tracking pipeline

The following example illustrates how to use the `facenet_pytorch` python package to perform face detection and tracking on an image dataset using MTCNN.

In [1]:
from facenet_pytorch import MTCNN
import torch
import numpy as np
#import mmcv
import cv2
from PIL import Image, ImageDraw
from IPython import display
import os,glob

/Users/rianbutala/.pyenv/versions/3.12.4/lib/python3.12/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


#### Determine if an nvidia GPU is available

In [2]:
device = torch.device('cpu')
print('Running on device: {}'.format(device))

Running on device: cpu


#### Define MTCNN module

Note that, since MTCNN is a collection of neural nets and other code, the device must be passed in the following way to enable copying of objects when needed internally.

See `help(MTCNN)` for more details.

In [3]:
mtcnn = MTCNN(keep_all=True, device=device)

#### Get a sample video

We begin by loading a video with some faces in it. The `mmcv` PyPI package by mmlabs is used to read the video frames (it can be installed with `pip install mmcv`). Frames are then converted to PIL images.

In [9]:
'''video = mmcv.VideoReader('video.mp4')
frames = [Image.fromarray(cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)) for frame in video]

display.Video('video.mp4', width=640)'''

#path = "/Users/rianbutala/Rian's projects/Coding/Facial Recognition/bse_face_recognition/img/train/notrian"
#save_path = "/Users/rianbutala/Rian's projects/Coding/Facial Recognition/bse_face_recognition/cropped/train/notrian"

path = "/Users/rianbutala/Rian's projects/Coding/Facial Recognition/bse_face_recognition/face_pictures/img/train/rian"
save_path = "/Users/rianbutala/Rian's projects/Coding/Facial Recognition/bse_face_recognition/face_pictures/cropped/train/rian"


os.chdir(path)

images = []
counter = 0

for file in glob.glob("*.jpeg"):
    with Image.open(file) as img:
        #img.show()
        images.append(file)
        print("parsed file count = " +str(counter))
        counter = counter + 1

for file in glob.glob("*.jpg"):
    with Image.open(file) as img:
        #img.show()
        images.append(file)
        print("parsed file count = " +str(counter))
        counter = counter + 1
for file in glob.glob("*.png"):
    with Image.open(file) as img:
        #img.show()
        images.append(file)
        print("parsed file count = " +str(counter))
        counter = counter + 1

print(type(images[0]))


parsed file count = 0
parsed file count = 1
parsed file count = 2
parsed file count = 3
parsed file count = 4
parsed file count = 5
parsed file count = 6
parsed file count = 7
parsed file count = 8
parsed file count = 9
parsed file count = 10
parsed file count = 11
parsed file count = 12
parsed file count = 13
parsed file count = 14
parsed file count = 15
parsed file count = 16
parsed file count = 17
parsed file count = 18
parsed file count = 19
parsed file count = 20
parsed file count = 21
parsed file count = 22
parsed file count = 23
parsed file count = 24
parsed file count = 25
parsed file count = 26
parsed file count = 27
parsed file count = 28
parsed file count = 29
parsed file count = 30
parsed file count = 31
parsed file count = 32
parsed file count = 33
parsed file count = 34
parsed file count = 35
parsed file count = 36
parsed file count = 37
parsed file count = 38
parsed file count = 39
parsed file count = 40
parsed file count = 41
parsed file count = 42
parsed file count = 4

#### Run video through MTCNN

We iterate through each frame, detect faces, and draw their bounding boxes on the video frames.

In [10]:

imgs =[]
#print('\rTracking frame: {}'.format(i + 1), end='')

# Detect faces
for count,img in enumerate(images):
    os.chdir(path)
    try:
        print(img)
        img = Image.open(img)
        boxes, _ = mtcnn.detect(img)

        # Draw faces
        frame_draw = img.copy()
        draw = ImageDraw.Draw(frame_draw)
        try:
            for box in boxes:
                draw.rectangle(box.tolist(), outline=(255, 0, 0), width=6)
                print(box)

            cropped_img = img.copy()
            cropped_img = cropped_img.crop(boxes[0])
            #d = display.display(cropped_img, display_id=True)
            os.chdir(save_path)
            cropped_img.save("img_"+"c"+str(count)+".jpeg")
            print("saved!! @ "+ "img_"+"c"+str(count)+".jpeg")


            # Add to frame list
            imgs.append(frame_draw.resize((640, 360), Image.BILINEAR))
            print('\nDone')
        except:
            print("caught!!")
    except:
        print("caught 2")
print("all done!!")

2024-06-17 13:01:44c14.jpeg
[739.7146606445312 599.3546752929688 1163.5928955078125 1174.5650634765625]
[1867.7041015625 394.45391845703125 1935.548583984375 479.439697265625]
saved!! @ img_c0.jpeg

Done
2024-06-17 13:03:35c108.jpeg
[989.1435546875 490.962158203125 1282.21240234375 884.2881469726562]
[1472.2567138671875 971.791259765625 1530.9891357421875 1051.0037841796875]
[87.7206802368164 665.8413696289062 122.23695373535156 711.1443481445312]
saved!! @ img_c1.jpeg

Done
2024-06-17 13:27:36c147.jpeg
[812.3345336914062 416.4891357421875 1152.7235107421875 860.2432250976562]
saved!! @ img_c2.jpeg

Done
2024-06-13 18:26:41c201.jpeg
[784.9450073242188 279.52099609375 1306.0421142578125 945.881591796875]
saved!! @ img_c3.jpeg

Done
2024-06-13 18:26:33c21.jpeg
[1100.34375 245.33241271972656 1533.2271728515625 784.2537231445312]
saved!! @ img_c4.jpeg

Done
2024-06-17 13:03:32c26.jpeg
[938.6510009765625 539.69287109375 1224.9033203125 914.7224731445312]
[1484.5792236328125 955.465698242187

In [19]:
'''frames_tracked = []
for i, frame in enumerate(frames):
    print('\rTracking frame: {}'.format(i + 1), end='')
    
    # Detect faces
    boxes, _ = mtcnn.detect(frame)
    
    # Draw faces
    frame_draw = frame.copy()
    draw = ImageDraw.Draw(frame_draw)
    for box in boxes:
        draw.rectangle(box.tolist(), outline=(255, 0, 0), width=6)
    
    # Add to frame list
    frames_tracked.append(frame_draw.resize((640, 360), Image.BILINEAR))
print('\nDone')'''

"frames_tracked = []\nfor i, frame in enumerate(frames):\n    print('\rTracking frame: {}'.format(i + 1), end='')\n    \n    # Detect faces\n    boxes, _ = mtcnn.detect(frame)\n    \n    # Draw faces\n    frame_draw = frame.copy()\n    draw = ImageDraw.Draw(frame_draw)\n    for box in boxes:\n        draw.rectangle(box.tolist(), outline=(255, 0, 0), width=6)\n    \n    # Add to frame list\n    frames_tracked.append(frame_draw.resize((640, 360), Image.BILINEAR))\nprint('\nDone')"

#### Display detections

In [20]:
#d = display.display(imgs[0], display_id=True)
#for img in imgs:
#    display.display(img,display_id=True)

In [21]:
'''d = display.display(frames_tracked[0], display_id=True)
i = 1
try:
    while True:
        d.update(frames_tracked[i % len(frames_tracked)])
        i += 1
except KeyboardInterrupt:
    pass'''

'd = display.display(frames_tracked[0], display_id=True)\ni = 1\ntry:\n    while True:\n        d.update(frames_tracked[i % len(frames_tracked)])\n        i += 1\nexcept KeyboardInterrupt:\n    pass'

#### Save tracked video

In [22]:
'''dim = frames_tracked[0].size
fourcc = cv2.VideoWriter_fourcc(*'FMP4')    
video_tracked = cv2.VideoWriter('video_tracked.mp4', fourcc, 25.0, dim)
for frame in frames_tracked:
    video_tracked.write(cv2.cvtColor(np.array(frame), cv2.COLOR_RGB2BGR))
video_tracked.release()'''

"dim = frames_tracked[0].size\nfourcc = cv2.VideoWriter_fourcc(*'FMP4')    \nvideo_tracked = cv2.VideoWriter('video_tracked.mp4', fourcc, 25.0, dim)\nfor frame in frames_tracked:\n    video_tracked.write(cv2.cvtColor(np.array(frame), cv2.COLOR_RGB2BGR))\nvideo_tracked.release()"